baseURL = "https://judywan9.github.io"
languageCode = "en-US"
title = "Judy One"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "image/profile.jpg"
  author = "Judy Wang"
  description = "Life Logging"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "iamwangdi@live.cn"
  LinkedIn      = "iamwangdi"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
